add lazy typist functionality to unitTest

diff --git a/unitTest b/unitTest
--- a/unitTest
+++ b/unitTest
@@ -1,10 +1,11 @@
 #!/bin/bash
 
-
+#TODO(HARVEY): use file to check file type instead
+#TODO(HARVEY): default to tests folder
 # Runs any compiled java class file in the Tomcat Webapps workspace
 # USAGE: unitTest [ filename.class ]
-# e.g. unitTest CalculatorTest.class
-# e.g. unitTest tests/QueryUtilsTest.class
+# e.g. unitTest CalculatorTest
+# e.g. unitTest QueryUtilsTest
 
 if [ "$1" == "--help" ] && [ $# -eq 1 ]; then
 	echo "Usage: unitTest [ filename.class ]"
@@ -24,18 +25,30 @@ if [ "$OSTYPE"  == "linux-gnu" ]; then
     master_path=$(git rev-parse --show-toplevel | sed 's/^C\:/c/g')
 fi
 class_path="ROOT/WEB-INF/classes"
+package_folder="tests"
 class_name="$1"
+ext=".class"
 #trim .class extension from file
-ext=$(echo $class_name | sed 's/\(.*\)\./\1:/' | cut -f2 -d":")
+#ext=$(echo $class_name | sed 's/\(.*\)\./\1:/' | cut -f2 -d":")
 
-if [ "$ext" != "class" ]; then
-	echo "$class_name is not a '.class' file"
+#if [ "$ext" != "class" ]; then
+#	echo "$class_name is not a '.class' file"
+#	exit 1
+#fi
+
+
+#if file does not exist in specified filepath
+if [ ! -f "$master_path/$class_path/$package_folder/$class_name$ext" ]; then
+        echo "file not found: $master_path/$class_path/$package_folder/$class_name$ext"
 	exit 1
 fi
 
-#if file does not exist in specified filepath
-if [ ! -f "$master_path/$class_path/$class_name" ]; then
-	echo "file not found: $master_path/$class_path/$class_name"
+#Use file to check file type
+file_type=$(file --mime-type "$master_path/$class_path/$package_folder/$class_name$ext" | cut -f2 -d':' | cut -f2 -d' ')
+class_type="application/x-java-applet"
+if [ "$file_type" != "$class_type" ]; then
+	echo "$class_name is not a '$ext' file"
+	echo "$file_type not $class_type"
 	exit 1
 fi
 
@@ -48,9 +61,9 @@ for file in $(ls $master_path/$lib_path/*.jar); do
 done
 
 #if there are / in the class name, replace all of them with .
-class=$(echo $class_name | sed 's_/_._g')
+class=$(echo "$package_folder/$class_name" | sed 's_/_._g')
 #grab class name without extension .class
-class=$(echo $class | sed 's/\(.*\)\./\1:/' | cut -f1 -d":")
+#class=$(echo $class | sed 's/\(.*\)\./\1:/' | cut -f1 -d":")
 
 #junit main class for testing
 printf " org.junit.runner.JUnitCore $class" >> java2Makefile
